# Generated by Django 4.2.11 on 2024-04-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Haryana', 'Haryana'), ('Punjab', 'Punjab')], default='Haryana', max_length=100),
            preserve_default=False,
        ),
    ]
